### PR TITLE
Point to rpm not repo

### PR DESCRIPTION
**Pull request by incognick**
I found this example [here](https://dky.io/puppet/how-to-install-a-rpm-from-url-using-puppet/) 

Resolves https://github.com/VividCortex/artifacts/issues/2098

### CODE REVIEW

**Review by gkristic-vc — COMMENTED** [review]
Looks reasonable to me, but I've never used Puppet. Did you test it?

**Comment by incognick** [comment]
Me either. I did some basic lint checking that found the naming convention was wrong so I resolved that before this PR. 

Should I setup a couple servers and test it? I think puppet requires a server where an agent runs and then I can set up another server as a target. Probably a couple hours of effort

**Comment by gkristic-vc** [comment]
If you can in a couple hours, I think it's worth doing.

-- 
-- 
This email may be confidential or privileged.  If you received this 
communication by mistake, please don't forward it to anyone else. Please 
erase all copies and attachments, and please let me know that it went to 
the wrong person.

**Comment by incognick** [comment]
@gkristic-vc This is more complex than I thought.  I'm having SSL certificate issues with puppet so the agent cannot get a certificate from the master.  I've looked at quite a few sites, tried numerous things and can't figure it out. I don't feel this is time well spent.

**Comment by gkristic-vc** [comment]
I just want to make sure we don't claim this is done and then a customer finds it's not. @seaparks I'll leave this up to you.

**Comment by incognick** [comment]
Maybe we should remove the puppet example and simply provide the RPM url?  Do we give examples of other orchestration tools such as Chef or Ansible?

**Comment by seaparks** [comment]
@incognick -- our docs instructions on this topic are here: https://docs.vividcortex.com/getting-started/advanced-installation/#installing-with-chef . not sure if that's what you're looking for / answers your question.

**Comment by incognick** [comment]
@seaparks That is what I'm suggesting - we remove the Puppet example since we can't verify if our example is correct (we don't use puppet nor have a puppet cluster setup). The first customer that tries it and finds a problem will report it.  

On the other hand, if we specify just the RPM, we can suggest to them to simply install the rpm via their configuration management tool of choice

**Comment by seaparks** [comment]
Thanks @incognick for the background -- @gkristic-vc I think we should pull anything that we can't verify that it works. If that means we just provide the RPM somewhere but not the puppet stuff, that's fine by me for now and we can re-address if we get feedback from larger clients that this is required.

What would taking this path mean? For example, what would we hide in github, and what would I have to change in the documentation?

**Comment by gkristic-vc** [comment]
Let's briefly talk about this tomorrow.

**Comment by incognick** [comment]
@gkristic-vc This has been verified.

**Pull request merged**
